logfellow/logstash-logback-encoder

README.md, src/main/java/net/logstash/logback/LogstashAbstractFormatter.java, src/main/java/net/logstash/logback/LogstashAccessFormatter.java, src/main/java/net/logstash/logback/fieldnames/LogstashAccessFieldNames.java, src/main/java/net/logstash/logback/fieldnames/LogstashCommonFieldNames.java, src/test/java/net/logstash/logback/encoder/LogstashAccessEncoderTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Disabled by default (because it can be quite big), but it can be activated with:
<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
<fieldNames>
<fieldsRequestHeaders>@fields.request_headers</fieldsRequestHeaders>
<fieldsResponseHeaders>@fields.response_headers</fieldsResponseHeaders>
</fieldNames>
</encoder>
=> Add support for logging request & response headers (in logstash-access)

src/main/java/net/logstash/logback/layout/CompositeJsonLayout.java, src/test/java/net/logstash/logback/layout/CompositeJsonLayoutTest.java
parentheses were missing in the way the length of the message was computed when setting only a prefix or a suffix layout inside a CompositeJsonLayout.
=> fixed setting a prefix without a suffix on the CompositeJsonLayout

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
Let logback/joran handles the string/Charset conversion and make sure getter/setter are of the same type so the property is correctly recognised by Joran during configuration.
See https://github.com/logstash/logstash-logback-encoder/issues/121 for more information.
=> Fix KeepAliveCharset configuration property (gh121)

pom.xml, src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
See https://github.com/logstash/logstash-logback-encoder/issues/115
This PR holds a first quick-and-dirty attempts to implement the feature. Please, have a look for review and comments.
A comma separated list of `host:port` pairs can be specified via the `<hostAddresses>` configuration property. The first host is the primary, while the others are considered secondaries.
The appender tries to connect to the primary and fallbacks to a secondary when unavailable. Hosts are tried in the order they appear in the `<hostAddresses>` property.
When connected to a secondary, the appender tries to reconnect to the primary after `<reconnectionToPrimaryDelay>` time.
=> TcpSocketAppender Failover implementation

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
IMHO the stack trace is of limited value here. We're using destinations that will never resolve in DNS that's only used in local development (e.g. references to docker container names). 
Other warnings emitted on initializing logback typically don't include stack traces, e.g:
`13:16:49,461 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.`
=> Don't log stacktrace on unknown host exception

README.md
Hello.
I found duplicate characters "<<" in README.md.
Thanks.
=> Fix missing spell in README.md

pom.xml
XML external entity (XXE) vulnerability in XmlMapper in the Data format
extension for Jackson (aka jackson-dataformat-xml) allows attackers to
have unspecified impact via unknown vectors.
fasterxml:jackson:2.7.3 and previous versions are affected.
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-3720
=> Update jackson dependency due to CVE-2016-3720

README.md, src/main/java/net/logstash/logback/pattern/AbstractJsonPatternParser.java, src/test/java/net/logstash/logback/pattern/AbstractJsonPatternParserTest.java
Hi, I have added support for using #asJson issue: #208 
`#asJson` also supports conversion out of the box to any primitive type like **int**, **double** or **boolean**.
It's useful specially when using with the **message** field:
```xml
<encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
<providers>
<pattern><pattern>{
"bytes_sent_str": "%b",
"bytes_sent_long": "#asJson{%b}",
"has_message": "#asJson{%X{hasMessage}}",
"raw_message": "#asJson{%m}"
}</pattern></pattern>
</providers>
</encoder>
```
...will produce something like:
```
{
"bytes_sent_str": "1024",
"bytes_sent_long": 1024,
"has_message": true,
"raw_message": { "type":"example", "msg":"example of json message with type" }
}
```
=> Implementation of feature #asJson

pom.xml
Addresses Jackson Deserializer security vulnerability. Refer issue #230
=> Update Jackson version to 2.8.9

pom.xml
com.fasterxml.jackson had a security vulnerability labeled CVE-2017-15095. It was addressed in com.fasterxml.jackson versions 2.8.10 and 2.9.1 and later. This commit updates the logback encoder plugin to the latest 2.8.x version of com.fasterxml.jackson to address that.
=> Update com.fasterxml.jackson version to 2.8.11

pom.xml
This is necessary for structured arguments or creating custom field types.
Just a simple change to OSGi Manifest file
=> Added more packages to OSGI's exports

src/main/java/net/logstash/logback/decorate/ReplaceCharsJsonFactoryDecorator.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Solves #279 . Configuration example:
```
<encoder class="net.logstash.logback.encoder.LogstashEncoder">
<jsonFactoryDecorator class="net.logstash.logback.decorate.ReplaceCharsJsonFactoryDecorator">
<replace>
<targetNumber>10</targetNumber> 
<replacement>===</replacement>
</replace>
</jsonFactoryDecorator>
</encoder>
```
=> Configurable char replacement JsonFactoryDecorator 

src/test/java/net/logstash/logback/argument/StructuredArgumentsToStringTest.java
When configured, this provider outputs an incrementing sequence number for every log event.
This can be useful to detect gaps in your log stream and help identify problems with your log transport.
It also makes reading logs easier as it helps the reader to distinguish between missing log lines and flaky system behavior.
=> Don't fill in stack trace in test exception

pom.xml
Rather simple change that moves `logback-core` to `provided` scope. Given `logstash-logback-encoder` is used from within logback itself.
=> Fix #288: move logback-core to provided scope

README.md, src/main/java/net/logstash/logback/LogstashFormatter.java, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java, src/test/resources/logback-test.xml
This behavior mimics the includeMdc behavior and causes
the tags serialization to be skipped.
=> Add support for excluding markers via <includeTags>false</includeTags>

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
When SSL is enabled, we should trigger the SSL handshake as soon as the socket is connected.
This way if the handshake fails the socket is declared unconnected.
(Fix for #327)
=> Trigger SSL handshake as soon as the socket is connected (#327)

pom.xml
Jackson 2.9.9 contains a few vulnerabilities reported by Snyk:
```
✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
Description: Deserialization of Untrusted Data
Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450207
Introduced through: net.logstash.logback:logstash-logback-encoder@6.1
From: net.logstash.logback:logstash-logback-encoder@6.1 > com.fasterxml.jackson.core:jackson-databind@2.9.9
✗ High severity vulnerability found in com.fasterxml.jackson.core:jackson-databind
Description: Deserialization of Untrusted Data
Info: https://snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-450917
Introduced through: net.logstash.logback:logstash-logback-encoder@6.1
From: net.logstash.logback:logstash-logback-encoder@6.1 > …
```
=> Update Jackson to 2.9.9.3

src/main/java/net/logstash/logback/LogstashAccessFormatter.java, src/main/java/net/logstash/logback/encoder/LogstashAccessEncoder.java, src/main/java/net/logstash/logback/layout/LogstashAccessLayout.java
This PR adds the same functionality to the access logger that is already implemented in the standard JSON logger.
If one set the element `includeContext` to `false` the context of the logger is not added to the JSON output.
```xml
<configuration>
<statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener"/>
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder">
<timeZone>UTC</timeZone>
<includeContext>false</includeContext>
<fieldNames>
<requestHeaders>request_headers</requestHeaders>
<responseHeaders>response_headers</responseHeaders>
</fieldNames>
</encoder>
</appender>
<appender-ref ref="STDOUT"/>
</configuration>
```
=> Added isIncludeContext check to access logger encoder.

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/main/java/net/logstash/logback/marker/LogstashBasicMarker.java, src/test/java/net/logstash/logback/ConfigurationTest.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java, src/test/java/net/logstash/logback/encoder/CompositeJsonEncoderTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Hi，
Is it necessary to replace `Charset.forName("UTF-8")` or some codes like `new String(encoded, "UTF-8")` to the constant variable StandardCharsets.UTF_8 which JDK 7 has provided
=> Replace `Charset.forName("UTF-8")` to `StandardCharsets.UTF_8`

README.md, src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventJsonProviders.java, src/main/java/net/logstash/logback/composite/loggingevent/RootStackTraceElementJsonProvider.java, src/main/java/net/logstash/logback/fieldnames/LogstashFieldNames.java, src/main/java/net/logstash/logback/fieldnames/ShortenedFieldNames.java, src/test/java/net/logstash/logback/composite/loggingevent/ExceptionRootCauseMethodNameJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/RootStackTraceElementJsonProviderTest.java
Hi 👋
I'm opening a draft for a new json provider.
It complements existing ones (ThrowableRootCauseClassNameJsonProvider, StackTraceJsonProvider, ...).
This provides details about the context of the exception, ie, it doesn't tell us that a NullPointerException occurred but rather that it occurred in MyClass.myMethod().
For example, `MyClass.doSomething()` calling `MyOtherClass.doSomethingRisky()` which throws an error will produce the following output.
```json
{
"root_stack_trace_element":{
"class_name":"com.example.stacktraces.MyOtherClass",
"method_name":"doSomethingRisky"
}
}
```
=> Add new json provider to log root stack trace elements

README.md, src/main/java/net/logstash/logback/LogstashFormatter.java, src/main/java/net/logstash/logback/composite/JsonWritingUtils.java, src/main/java/net/logstash/logback/composite/loggingevent/MessageJsonProvider.java, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java, src/test/java/net/logstash/logback/composite/loggingevent/MessageJsonProviderTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
This PR adds an option to output the `"message"` field as a JSON array, instead of a JSON string.
For example, with either of these logging statements:
```java
logger.error("first line{}second line", System.lineSeparator());
// or
logger.error("first line\nsecond line");
// or
logger.error("first line\r\nsecond line");
```
The output is consistent:
```yaml
{
"message": [
"first line",
"second line"
],
...
}
```
This provides an unambiguous parsing format on the target system instead of relying on the source platform's newline representation.
=> Add option to split log messages on newlines - fixes #404

README.md
This PR adds the one example for the adjustment of the `stack_trace` field name into the README.
It took me quite a little bit of time to understand how this XML needs to be called:
* `<stacktrace />`
* `<stackTrace />`
* `<stack_trace />`
I think this simplifies the adjustment of it a little (it would certainly have helped me via looking into the example).
=> Added stacktrace field name adjustment example

src/main/java/net/logstash/logback/composite/CompositeJsonFormatter.java
In general `JsonGenerator` should be closed, so that Jackson can recycle buffers etc..
It looks like `logstash-logback-encoder` does it own buffer management, so I am not sure if it is necessary.
Sorry for the noise if this is irrelevant.
=> Close JsonGenerators after usage.

src/main/java/net/logstash/logback/appender/DelegatingAsyncDisruptorAppender.java, src/test/java/net/logstash/logback/appender/DelegatingAsyncDisruptorAppenderTest.java
This PR addresses the following issues:
- Wrap calls to appenders within a try/catch block and make sure exceptions thrown by one does not prevent other appenders from receiving the event (#456).
- Flush appenders at end of batch only if they are started (#456).
- OutputStreamAppender may occasionally return a null OutputStream (#455)
- Flush appenders implementing java.io.Flushable (#454)
=> Make DelegatingAsyncDisruptorAppender more resilient to exceptions + flush Flushable appenders at end of batch

pom.xml
Use the `org.eclipse.m2e:lifecycle-mapping` plugin to configure M2E to ignore execution of the `maven-license-plugin`.
Related issue: #468
=> Configure M2E to ignore executions of the maven-license-plugin

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java
empty-array is recommended in modern java
```java
Object[] objArray = collection.toArray(new Object[0]);
```
- **intellij** insepction
>There are two styles to convert a collection to an array: either using a pre-sized array (like c.toArray(new String[c.size()])) or using an empty array (like c.toArray(new String[0]).
In older Java versions using pre-sized array was recommended, as the reflection call which is necessary to create an array of proper size was quite slow. However since late updates of OpenJDK 6 this call was intrinsified, making the performance of the empty array version the same and sometimes even better, compared to the pre-sized version. Also passing pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and …
=> Avoid calling 'toArray' with pre-sized array argument

README.md
should be runtime, not compile dependencies.
=> README maven logger should be runtime, not compile

src/main/java/net/logstash/logback/marker/LogstashBasicMarker.java, src/main/java/net/logstash/logback/marker/LogstashMarker.java, src/main/java/net/logstash/logback/marker/MapEntriesAppendingMarker.java, src/main/java/net/logstash/logback/marker/ObjectAppendingMarker.java, src/main/java/net/logstash/logback/marker/ObjectFieldsAppendingMarker.java, src/main/java/net/logstash/logback/marker/RawJsonAppendingMarker.java, src/main/java/net/logstash/logback/marker/SingleFieldAppendingMarker.java, src/test/java/net/logstash/logback/marker/MarkersTest.java
Previously, if multiple empty markers with references were aggregated, only one marker would be be returned as the aggregate (and the other's references would be lost).
Fixes #527
=> Fix marker aggregation when multiple empty markers are aggregated.

src/main/java/net/logstash/logback/decorate/CharacterEscapesJsonFactoryDecorator.java, src/main/java/net/logstash/logback/decorate/CompositeJsonFactoryDecorator.java, src/main/java/net/logstash/logback/decorate/EscapeNonAsciiJsonFactoryDecorator.java, src/main/java/net/logstash/logback/decorate/JsonFactoryDecorator.java
All implementations should override `JsonFactoryDecorator.decorate(JsonFactory)` instead
Part of #470
=> Remove JsonFactoryDecorator.decorate(MappingJsonFactory)

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
Use destination instead
Part of #470
=> Remove LogstashTcpSocketAppender.remoteHost/port

pom.xml
=> Bump checkstyle to 8.44 (from 8.29)

.gitignore, pom.xml
- exclude MANIFEST from shaded jars to make sure we keep only the one from the project in the final result
- explicitly configure the plugin to <include> the Disruptor and <exclude> all the other dependencies (if not, new project dependencies will be shaded as well if the plugin configuration is not updated)
- produce shaded source as well (handy when debugging applications making use of the library)
Related issue: #553
=> Maven Shade: exclude MANIFEST and produce shaded SOURCE jar

src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
Not easy to reproduce... even more when we don't have to full test execution logs :-(
I managed to get an issue twice locally and I think I could fix them. The idea behind the fix is to wait until the  `listener#connectionOpen()` before evaluating the asserts. If we start earlier, the internal state may not yet be 100% stable...
Related issue: #560
=> Attempt at fixing #560

README.md, pom.xml, src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java, src/test/java/net/logstash/logback/appender/AsyncDisruptorAppenderTest.java
Please have a look at this first draft implementation for #559.
In short, the appender supports two distinct operation modes (set via `asyncMode`):
- `DROP` (the default): the appender drops events when the ring buffer is full. This is the legacy behaviour.
- `BLOCK`: the appending thread is blocked when the buffer is full until some free space becomes available. An optional timeout can be specified using the `retryTimeout` configuration property (disabled by default).
The RingBuffer does not allow me to "publish with a timeout" - it offers either a "try publish" or a "publish". The later blocks indefinitely until there is enough space in the buffer to accept the event. Even worst, waiting threads are not unblocked when the disruptor is shutdown.
Instead, I decided to tryPublish and sleep …
=> Async append blocking with timeout

src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java, src/test/java/net/logstash/logback/appender/AsyncDisruptorAppenderTest.java, src/test/java/net/logstash/logback/appender/DelegatingAsyncDisruptorAppenderTest.java
This PR modifies the `EventClearingEventHandler` such that it notifies the `BatchEventProcessor` that the sequence has progressed after every event. Without this callback the sequence would not be progressed until the batch has completely finished.
@philsttr Could you have a look and tell me what you think about it?
=> Release/clear LogEvent early before end of batch (gh568)

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
=> Create Disruptor with a ThreadFactory instead of ExecutorService

pom.xml
Upgrade maven-enforcer-plugin to 3.0.0 and add an <execution> section to trigger the execution of the plugin during build.
This PR addresses issues #580 and #579.
=> Upgrade maven-enforcer-plugin to 3.0.0

pom.xml
=> Prevent duplicate generation of sources and javadocs artefacts during a release build

.github/workflows/build.yml
- Enable caching of local maven repo + wrapper
- Use "adopt" JDK instead of "Zulu"
- Speedup Maven execution by limiting the compiler at tier 1 (java process won't last long enough to benefit from more aggressive optimisations)
closes #597
=> Setup Github "cache" action

src/main/java/net/logstash/logback/marker/LogstashBasicMarker.java, src/main/java/net/logstash/logback/marker/LogstashMarker.java, src/test/java/net/logstash/logback/marker/MarkersTest.java
=> Refresh LogstashBasicMarker implementation and remove synchronisation

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
Keep current behaviour for backward compatibility.
Emit a WARN status when the property is set.
fixes #633
=> Deprecate AbstractLogstashTcpSocketAppender#secondaryConnectionTTL

src/main/java/net/logstash/logback/marker/ObjectFieldsAppendingMarker.java
This PR adresses issue #642.
The primary objective of these changes is to maintain a separate cache of JsonProvider per ObjectMapper instance.
It also contains the following changes that are functional equivalent as the original implementation but delegate more of the work to Jackson itself:
- do not create a new instance of SerializerProvider ourselves but instead use `ObjectMapper#getSerializerProviderInstance` introduced in Jackson 2.7
- do not create a JsonSerializer for the class to serialize ourselves but instead delegate to Jackson `SerializerProvider#findValueSerializer(Class)` and therefore leverage its internal cache
=> Cache JsonSerializer "per" ObjectMapper

src/main/java/net/logstash/logback/composite/ContextJsonProvider.java, src/main/java/net/logstash/logback/fieldnames/LogstashCommonFieldNames.java, src/main/java/net/logstash/logback/fieldnames/LogstashFieldNames.java
=> Allow FieldNames to override the field name of ContextJsonProvider when used in the context of IAccessEvent

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java, src/main/java/net/logstash/logback/appender/DelegatingAsyncDisruptorAppender.java, src/test/java/net/logstash/logback/appender/AsyncDisruptorAppenderTest.java
(1)
Introduce a `#createEventHandler()` method to provide the EventHandler instead of a simple setter method.
Reasons include:
- providing an EventHandler is mandatory. Using an abstract method makes obvious one is required whereas a simple setter supposes it may be optional (until start() is called... which is at runtime, and therefore too late).
- inheriting classes must call `#setEventHandler()` in their constructor - the base class does not have control as to when the handler is actually created. Also, if a class wants to extend `AsyncDisruptorAppender` to provide its own implementation, a first handler will be created and set by AsyncDisruptorAppender's constructor before it is overridden by the one provided by the extending class. Using a factory method solves that issue.
- …
=> Refactor AsyncAppenderDisruptor event handling

.github/workflows/build.yml, src/main/java/net/logstash/logback/appender/destination/RandomDestinationConnectionStrategy.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java, src/test/java/net/logstash/logback/appender/destination/RandomDestinationConnectionStrategyTest.java
=> Build with Java 17 LTS

README.md, src/main/java/net/logstash/logback/composite/FormattedTimestampJsonProvider.java, src/main/java/net/logstash/logback/util/TimeZoneUtils.java, src/test/java/net/logstash/logback/util/TimeZoneUtilsTest.java
=> Throw IllegalArgumentException at invalid time zone textual representation instead of defaulting to GMT

src/main/java/net/logstash/logback/util/ReusableByteBufferPool.java, src/test/java/net/logstash/logback/util/ReusableByteBufferPoolTest.java
`ReusableByteBuffer`s must be properly reset when returned to the pool.
=> "reset()" ReusableByteBuffers when they are returned to the pool

README.md, src/main/java/net/logstash/logback/mask/MaskingJsonGenerator.java, src/test/java/net/logstash/logback/mask/MaskingJsonGeneratorDecoratorTest.java
Previously, masking of a single value would stop after the first ValueMasker returned a masked value.
This meant that only one ValueMasker would process a string.
Now, all ValueMaskers are given the opportunity to process a value, which means that multiple substrings can be masked independently by different ValueMaskers
Fixes #690
=> Allow masking of multiple substrings

.github/workflows/build.yml, README.md, pom.xml
Previously, I merged #668, which bumps jackson to 2.13.0.
In this PR, I have added an additional GitHub workflow step that will run tests against jackson 2.12.5 (without recompiling).  Running these tests ensures that even though logstash-logback-encoder is compiled against jackson 2.13.0, logstash-logback-encoder continues to work with jackson 2.12.5 at runtime.   If users need jackson 2.12.5, they can use dependencyManagement to pin jackson back to 2.12.5.
Note that logstash-logback-encoder is not compatible with jackson 2.11.x (the tests fail due to `java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/filter/TokenFilter$Inclusion`)
I could not find a way to run the tests against both jackson 2.13.0 and 2.12.5 in a single maven command execution.  So, I had to add an additional …
=> Run tests against Jackson 2.12 to ensure runtime compatibility

.github/workflows/build.yml, pom.xml
=> Integrate Codecov to the build procedure

README.md, src/main/java/net/logstash/logback/composite/AbstractFormattedTimestampJsonProvider.java, src/main/java/net/logstash/logback/composite/FastISOTimestampFormatter.java, src/test/java/net/logstash/logback/composite/FastISOTimestampFormatterTest.java, src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProviderTest.java
The FastISOTimestampFormatter is a fast alternative to Java's DateTimeFormatter for the most commonly used ISO formats, i.e.:
- ISO_OFFSET_DATE_TIME
- ISO_ZONED_DATE_TIME
- ISO_LOCAL_DATE_TIME
- ISO_DATE_TIME
- ISO_INSTANT
Instead of computing every date/time fields every time it is invoked like the standard DateTimeFormatter does, the fast formatter remembers the previous formatted value and uses it to replace only the second and millis parts if the next timestamp to format is within the same minute.
This new formatter is currently used only when the `FormattedTimestampJsonProvider` is configured with one of default format listed above (expressed between `[]` in the configuration). A standard DateTimeFormatter is used for the other standard formats or if a custom pattern is configured …
=> FastISOTimestampFormatter as a fast alternative to Java's DateTimeFormatter for standard ISO formats

src/main/java/net/logstash/logback/marker/ObjectAppendingMarker.java, src/main/java/net/logstash/logback/marker/RawJsonAppendingMarker.java, src/main/java/net/logstash/logback/marker/SingleFieldAppendingMarker.java
`ObjectAppendingMarker#getFieldValue()` should ideally return the value of the `fieldValue` property without transformation. This method is intended to be used by `SingleFieldAppendingMarker#selfToString()` that already takes care of converting the value into a String.
closes #719
=> getFieldValue() should return `fieldValue` without transforming it into a String

src/main/java/net/logstash/logback/composite/AbstractCompositeJsonFormatter.java, src/main/java/net/logstash/logback/composite/JsonWritingUtils.java, src/main/java/net/logstash/logback/pattern/AbstractJsonPatternParser.java, src/main/java/net/logstash/logback/util/SimpleObjectJsonGeneratorDelegate.java, src/test/java/net/logstash/logback/util/SimpleObjectJsonGeneratorDelegateTests.java
Wrap the JsonGenerator with an optimized version of the writeObject() method that tries to call the appropriate write() method for the giveb untype Object and delegate to the underlying JsonGenerator as fallback.
Without this optimisation the writeObject() delegates to the underlying Codec which is less effective for simple types (String, Numbers, Boolean, byte[], JsonNode, etc) both in terms of CPU and temporary memory allocations.
Until now only the AbstractJsonPatternParser was using this optimisation. This commit moves it directly inside the JsonGenerator so it can benefit to any JsonProvider.
=> Custom JsonGenerator with optimized writeObject() for simple object types

src/main/java/net/logstash/logback/composite/loggingevent/LoggerNameJsonProvider.java, src/test/java/net/logstash/logback/composite/loggingevent/LoggerNameJsonProviderTest.java
`ClassNameOnlyAbbreviator` should be used instead of `TargetLengthBasedClassNameAbbreviator` when the desired length is set to `0`.
Closes #747
=> Handle case when shortenedLoggerNameLength is set to 0 (zero)

README.md
Fixed link to "Event-specific Custom Fields" in a table in section "Providers for LoggingEvents".
=> Fixed wrong link in README.md for #event-specific-custom-fields

README.md, src/main/java/net/logstash/logback/pattern/EnhancedPropertyConverter.java, src/main/java/net/logstash/logback/pattern/LoggingEventJsonPatternParser.java, src/main/java/net/logstash/logback/pattern/PatternLayoutAdapter.java, src/test/java/net/logstash/logback/pattern/LoggingEventJsonPatternParserTest.java
The behaviour of the `%property{key}` conversion specifier is slightly modified to return an empty string when the property is not defined instead of `null` as it normally does. Assuming the "foo" property does not exist, the following configuration:
```xml
<pattern>
{ "foo": "%property{foo}" }
</pattern>
```
... will produce something like this:
```json
{ "foo": "" }
```
... instead of:
```json
{ "foo": "null" }
```
The `foo` property will now be successfully omitted when `omitEmptyField` is `true`.
The property conversion specifier now also accepts an optional default value to use when the property does not exist. Assuming the property "foo" is not defined, `%property{foo:-bar}` will return `bar` instead of an empty string.
People wanting to revert to the original behaviour of returning …
=> Make "%property{key}" return an empty string instead of "null" when used in PatternJsonProvider

README.md, src/main/java/net/logstash/logback/pattern/AbstractJsonPatternParser.java, src/test/java/net/logstash/logback/pattern/AbstractJsonPatternParserTest.java
Add support for `#asNullIfEmpty{...}` operation in PatternJsonProvider.
=> 773 PatternJsonProvider: provide a "asNullIfEmpty{...}" operation

pom.xml
Fetch Logback javadoc from https://javadoc.io instead of from Logback’s website:
- /package-list not available anymore from the official location
- the official website contains the doc for the very latest released version only without history
=> Fetch Logback javadoc from https://javadoc.io

.github/workflows/build.yml, pom.xml
- Build against Logback 1.3.0
- Execute backward compatibility tests against latest Logback 1.2.x
- Comment links to Logback javadoc (generation fails under Java8 because logback docs have replace "package-list" by "element-list")
=> Bump to Logback 1.3.0-beta0

README.md, src/main/java/net/logstash/logback/composite/AbstractFormattedTimestampJsonProvider.java, src/main/java/net/logstash/logback/composite/FastISOTimestampFormatter.java, src/main/java/net/logstash/logback/composite/accessevent/AccessEventFormattedTimestampJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProvider.java, src/main/java/net/logstash/logback/util/LogbackUtils.java, src/test/java/net/logstash/logback/composite/FastISOTimestampFormatterTest.java, src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProviderTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Leverage the new `ILoggingEvent#getInstant()` method introduced in Logback 1.3 to provide timestamp with nanoseconds precision.
closes #829
=> gh829 timestamp nanos

src/main/java/net/logstash/logback/composite/loggingevent/LogstashMarkersJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/TagsJsonProvider.java, src/test/java/net/logstash/logback/composite/loggingevent/LogstashMarkersJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/TagsJsonProviderTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
ILoggingEvent can have multiple markers associated with them since Logback 1.3. To support this new behavior, a new ILoggingEvent#getMarkerList() method has been introduced. This change retrieves the Marker by calling this new method instead of the former #getMarker().
Test case have been adapted consequently. Also, tests have been modified to use concrete instances of LoggingEvent instead of mocking the used methods. This way we don’t make any assumption anymore about the actual behaviour of the LoggingEvent.
closes #831
=> Add support for multiple Markers attached to a single LoggingEvent

src/main/java/net/logstash/logback/mask/PathBasedFieldMasker.java, src/test/java/net/logstash/logback/mask/MaskingJsonGeneratorDecoratorTest.java
=> Fix absolute PathMask issue

README.md, src/main/java/net/logstash/logback/appender/destination/DestinationParser.java, src/test/java/net/logstash/logback/appender/destination/DestinationParserTest.java
Allow destinations to be specified with an IPv6 address enclosed between brackets (eg. `[2001:db8::1]:8080`).
closes #848
=> 848 ipv6 support in DestinationParser

README.md, src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
The initialSendDelay feature adds an optional wait time before a new connection can be used to write events.
closes #855
=> Implement initialSendDelay feature

README.md, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Make LogstashEncoder/Layout throw an IllegalArgumentException when an attempt is made to use the `<providers>` configuration property.
Also add a few words in the documentation about how to register additional JsonProvider to a LogstashEncoder.
=> 859 LogstashEncoder should throw IllegalArgumentException instead of logging an error status when attempting to use <providers>

src/main/java/net/logstash/logback/stacktrace/ShortenedThrowableConverter.java, src/main/java/net/logstash/logback/util/StringUtils.java, src/test/java/net/logstash/logback/stacktrace/ShortenedThrowableConverterTest.java, src/test/java/net/logstash/logback/util/StringUtilsTest.java
=> ShortenedThrowableConverter: <exclude> and <exclusions> are mutually exclusive (#876)

README.md, src/main/java/net/logstash/logback/util/StringUtils.java, src/test/java/net/logstash/logback/util/StringUtilsTest.java
Add a way to escape the comma in comma separated property values
Issue #847
=> Add a way to escape the comma in comma separated property values

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml
=> Bump github actions to their latest version

pom.xml, src/xsl/flatten-pom.xslt
=> Build consumer (flatten) POM

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, pom.xml
Still produce artifacts for Java 1.8.
Allows using maven plugins and test dependencies that require higher java versions.
Fixes #899
=> Bump build to JDK 17

src/main/java/net/logstash/logback/decorate/PrettyPrintingJsonGeneratorDecorator.java, src/test/java/net/logstash/logback/decorate/PrettyPrintingJsonGeneratorDecoratorTest.java
Add ability to customize the `PrettyPrinter` used by `PrettyPrintingJsonGeneratorDecorator`.
Specifically, add `rootSeparator` and `spacesInObjectEntries` fields.
Change default root separator used by the `PrettyPrinter` to an empty string to match the default `rootValueSeparator` used by the formatters. Previously, the default was a space (`" "`).  So this will slightly change the output when the `PrettyPrintingJsonGeneratorDecorator` is used. To revert to the old behavior, configure the decorator like this:
```xml
<jsonGeneratorDecorator class="net.logstash.logback.decorate.PrettyPrintingJsonGeneratorDecorator">
<rootSeparator>[SPACE]</rootSeparator>
</jsonGeneratorDecorator>
```
Requested in discussion #906
=> Add ability to customize the PrettyPrinter

src/main/java/net/logstash/logback/composite/AbstractCompositeJsonFormatter.java, src/main/java/net/logstash/logback/decorate/yaml/YamlJsonFactoryDecorator.java, src/test/java/net/logstash/logback/decorate/cbor/CborJsonFactoryDecoratorTest.java, src/test/java/net/logstash/logback/decorate/smile/SmileJsonFactoryDecoratorTest.java, src/test/java/net/logstash/logback/decorate/yaml/YamlJsonFactoryDecoratorTest.java
non-JSON generators were broken in 7.0 when a call to `generator.setRootValueSeparator` was introduced.  The non-JSON generators throw `UnsupportedOperationException` when `setRootValueSeparator` is invoked.
Handle the `UnsupportedOperationException` properly.
Also moved disabling the `FLUSH_PASSED_TO_STREAM` generator feature to prior to decoration, because the YAML generation needs this feature enabled to work properly.
Introduced basic tests for non-JSON generators to catch the above problems in the future.
Fixes #919
=> Fix non-JSON generators

.github/workflows/build.yml, README.md, pom.xml, src/main/java/net/logstash/logback/composite/AbstractSequenceJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/LogstashMarkersJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/TagsJsonProvider.java, src/main/java/net/logstash/logback/util/LogbackUtils.java, src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventFormattedTimestampJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/LogstashMarkersJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/SequenceJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/TagsJsonProviderTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java
Drop support for logback 1.2 in preparation for upcoming support for keyValue pairs in slf4j 2 and logback 1.3
=> Drop support for logback 1.2

src/main/java/net/logstash/logback/composite/AbstractCompositeJsonFormatter.java, src/test/java/net/logstash/logback/composite/loggingevent/LoggingEventCompositeJsonFormatterTest.java
The order in which `JsonGeneratorDelegate`s are chained currently leads to disregard the `writeObject` method of the `JsonGenerator` passed to `setJsonGeneratorDecorator`.
The internal `SimpleObjectJsonGeneratorDelegate` indeed intercepts `writeObject` for quite a number of concrete types:
https://github.com/logfellow/logstash-logback-encoder/blob/933a0f51c1bfefc838adee9982ad3537a08a39bd/src/main/java/net/logstash/logback/util/SimpleObjectJsonGeneratorDelegate.java#L38-L60
```java
// etc.
```
The present change therefore consists in moving any user-defined `JsonGenerator` to the top level of the delegation chain, leaving users the power (and therefore the responsibility) to adjust the output to their needs.
=> Honor overriden `writeObject` of `JsonGenerator` passed to `setJsonGeneratorDecorator`

README.md, src/main/java/net/logstash/logback/LogstashFormatter.java, src/main/java/net/logstash/logback/composite/loggingevent/MdcJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/mdc/BooleanMdcEntryWriter.java, src/main/java/net/logstash/logback/composite/loggingevent/mdc/DoubleMdcEntryWriter.java, src/main/java/net/logstash/logback/composite/loggingevent/mdc/LongMdcEntryWriter.java, src/main/java/net/logstash/logback/composite/loggingevent/mdc/MdcEntryWriter.java, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java, src/test/java/net/logstash/logback/ConfigurationTest.java, src/test/java/net/logstash/logback/composite/loggingevent/MdcJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/mdc/BooleanMdcEntryWriterTest.java, src/test/java/net/logstash/logback/composite/loggingevent/mdc/DoubleMdcEntryWriterTest.java, src/test/java/net/logstash/logback/composite/loggingevent/mdc/LongMdcEntryWriterTest.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java, src/test/resources/logback-test.xml
Solution proposal for issue https://github.com/logfellow/logstash-logback-encoder/issues/955
=> Add MDC entry writers to be able to convert values

src/main/java/net/logstash/logback/composite/loggingevent/AbstractThrowableClassNameJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/ThrowableClassNameJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/ThrowableRootCauseClassNameJsonProvider.java
Hi, I'm trying to customize the `throwable_class` field name but I found out that it isn't possible to extend the class `AbstractThrowableClassNameJsonProvider` because its abstract method `getThrowable` is package protected.
I think it doesn't make much sense to have a public abstract class that isn't really publicly extendable. Also this should align the class with the similar `AbstractThrowableMessageJsonProvider`, which already has its abstract method as protected.
As a temporary workaround I'm extending the class `ThrowableClassNameJsonProvider`, this way the package protected method is already implemented and the problem is circumvented.
Let me know what you think about this!
Bye!
=> Set AbstractThrowableClassNameJsonProvider.getThrowable as protected

README.md, src/main/java/net/logstash/logback/composite/loggingevent/mdc/RegexFilteringMdcEntryWriter.java, src/test/java/net/logstash/logback/ConfigurationTest.java, src/test/java/net/logstash/logback/composite/loggingevent/mdc/RegexFilteringMdcEntryWriterTest.java, src/test/resources/logback-test.xml
proposal for idea of regex filtering MDC entry writer from #972
=> Add composite MdcEntryWriter to filter MDC keys with regex

pom.xml
There was a regression introduced in 8.0 when building the source jar during releases when the maven-release-plugin was upgraded.
To simplify things, and avoid that in the future, I changed the build to always package the source jar.
Fixes #1036
=> Always build source jar
