README.md
The currently released version is 4.2, this is what most people would like to use.
=> Update README to show the latest release version

README.md, src/main/java/net/logstash/logback/argument/DefaultNamedArgument.java, src/main/java/net/logstash/logback/argument/FormattedNamedArgument.java, src/main/java/net/logstash/logback/argument/NamedArgument.java, src/main/java/net/logstash/logback/argument/NamedArguments.java, src/main/java/net/logstash/logback/composite/loggingevent/ArgumentsJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventJsonProviders.java, src/main/java/net/logstash/logback/fieldnames/LogstashFieldNames.java, src/test/java/net/logstash/logback/ConfigurationTest.java, src/test/java/net/logstash/logback/argument/NamedArgumentsToStringTest.java, src/test/java/net/logstash/logback/composite/loggingevent/ArgumentsJsonProviderTest.java, src/test/resources/logback-test.xml
=> Add Marker like support for arguments #99

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
=> Remove appender name from the error message (gh128)

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
=> Fix small typo in comments

src/main/java/net/logstash/logback/composite/loggingevent/AbstractThrowableClassNameJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/LoggingEventJsonProviders.java, src/main/java/net/logstash/logback/composite/loggingevent/ThrowableClassNameJsonProvider.java, src/main/java/net/logstash/logback/composite/loggingevent/ThrowableRootCauseClassNameJsonProvider.java, src/test/java/net/logstash/logback/ConfigurationTest.java, src/test/java/net/logstash/logback/composite/loggingevent/ThrowableClassNameJsonProviderTest.java, src/test/java/net/logstash/logback/composite/loggingevent/ThrowableRootCauseClassNameJsonProviderTest.java, src/test/resources/logback-test.xml
add Provider which puts the Throwable class name (actual and root cause) into fields so they can be listed/searched easily in ELK
=> add Throwable class name as field

src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
Two minor optimisations around the use of `destinations`.
Small contribution ;-)
=> Minor optimisations

pom.xml
Update to the latest jackson bom
=> Update jackson bom to 2.10.0

.github/workflows/build.yml
https://github.com/actions/setup-java
=> ci: enable Java build matrix

.github/workflows/build.yml
```
--no-transfer-progress
```
This flag reduces Maven verbosity.
=> ci: Maven --no-transfer-progress

.github/workflows/build.yml
Use a fixed version of Ubuntu.
=> ci: use 'ubuntu-20.04' instead of 'ubuntu-latest'

src/main/java/net/logstash/logback/appender/AsyncDisruptorAppender.java
Use threadNameFormat instead
Part of #470
=> Remove deprecated AsyncDisruptorAppender.threadNamePrefix

src/main/java/net/logstash/logback/LogstashFormatter.java, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java, src/test/java/net/logstash/logback/encoder/LogstashEncoderTest.java, src/test/resources/logback-test.xml
Use includeCallerData instead
Part of #470
=> Remove deprecated includeCallerInfo

src/main/java/net/logstash/logback/LogstashAccessFormatter.java, src/main/java/net/logstash/logback/LogstashFormatter.java, src/main/java/net/logstash/logback/composite/LogstashVersionJsonProvider.java, src/main/java/net/logstash/logback/encoder/LogstashAccessEncoder.java, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashAccessLayout.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java
Use writeVersionAsInteger with opposite value instead
Part of #470
=> Remove deprecated writeVersionAsString

pom.xml
=> Remove dependency-reduced-pom.xml as part of a normal “mvn clean” invocation

pom.xml
=> Move servlet-api to test scope

pom.xml
=> Additional enforcer rule to verify no dependencies have a bytecode higher than 1.8

pom.xml
=> Fix version of maven-deploy-plugin

pom.xml
=> Update javadoc link to Jackson packages 

.github/workflows/build.yml
=> Don’t trigger build on changes in Markdown files

README.md, src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java
=> Add a connectionTimeout configurable property

README.md, src/main/java/net/logstash/logback/appender/AbstractLogstashTcpSocketAppender.java, src/test/java/net/logstash/logback/appender/LogstashTcpSocketAppenderTest.java
=> Reject 'null' writeTimeout values

.github/workflows/build.yml
AdoptOpenJDK has been renamed to Adoptium Eclipse Temurin
=> Switch to temurin

README.md, src/main/java/net/logstash/logback/pattern/AbstractJsonPatternParser.java, src/test/java/net/logstash/logback/pattern/AbstractJsonPatternParserTest.java
=> Add a #asBoolean() pattern operation

src/main/java/net/logstash/logback/composite/FastISOTimestampFormatter.java
=> Detect suffix by looking for the first non-digit char instead of assuming the format

pom.xml
=> Bump to checkstyle 10.7.0

.github/dependabot.yml, .github/release.yml, .github/workflows/no-response.yml
=> Setup release notes categories for automatic release notes generation

src/main/java/net/logstash/logback/encoder/LogstashAccessEncoder.java, src/main/java/net/logstash/logback/encoder/LogstashEncoder.java, src/main/java/net/logstash/logback/layout/LogstashAccessLayout.java, src/main/java/net/logstash/logback/layout/LogstashLayout.java
Fixes typo in setProviders IllegalArugmentException message.
=> Fix typo in IllegalArgumentException message

.github/workflows/build.yml
=> Bump actions/upload-artifact@v4

.mvn/wrapper/maven-wrapper.properties, pom.xml
Also change license plugin config to use non-deprecated params
=> Bump maven to 3.9.9
